name: Run Tests

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build application
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: sqlite

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1']

    steps:
      - name: Install Prerequisites
        run: |
          mkdir -p ~/phpunit
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Setup PHP
        uses: shivammathur/setup-php@v2 # https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: log_errors=On, error_reporting=E_ALL, error_log=~/phpunit/php_errors.log, date.timezone=UTC, memory_limit=-1, max_execution_time=-1, display_errors=On, display_startup_errors=On
          extensions: dom, curl, libxml, bcmath, mbstring, zip, pcntl, intl, exif, pdo_mysql, redis
          tools: composer:v2
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Backend dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install Frontend dependencies
        run: npm i

      - name: Execute lint with Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Execute lint with ESLint
        run: npx eslint .

      - name: Create SQLite database file
        run: cp .env.example .env && touch database/database.sqlite

      - name: Migrate and Seed DB
        run: php artisan migrate:fresh --seed --env=testing && php artisan key:generate

      - name: Execute Tests
        run: php artisan test
